---
- name: Setup Apache2 and Deploy Website
  hosts: all  # Replace with your target hosts or group
  become: yes  # To run tasks with sudo privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - git
          - apache2
        state: present

    - name: Ensure Apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Clone the Git repository
      git:
        repo: 'https://github.com/subham-behera/Ask-Us'  # Replace with your Git repo URL
        dest: /tmp/website-repo
        version: master  # Replace with the branch or tag you need

    - name: Copy files from repo to /var/www/html
      copy:
        src: /tmp/website-repo/
        dest: /var/www/html/
        mode: 'u=rwX,g=rX,o=rX'  # Ensure correct permissions
        owner: www-data
        group: www-data
        remote_src: yes

    - name: Clean up the repository directory
      file:
        path: /tmp/website-repo
        state: absent
